# Generated by Django 4.1.5 on 2023-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کار ها'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.BooleanField(blank=True, default=True, verbose_name='انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان'),
        ),
    ]
